---
sidebar: sidebar 
permalink: oracle/azure-ora-nfile-usecase.html 
summary: Esta guía de mejores prácticas proporciona detalles de una solución para implementar y migrar la base de datos de Oracle en el almacenamiento de archivos de Azure NetApp y Azure VM. 
keywords: database, Oracle, Azure NetApp files, Azure 
---
= TR-4954: Prácticas recomendadas para la implementación y migración de bases de datos de Oracle para ANF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta guía de mejores prácticas proporciona detalles de una solución para implementar y migrar la base de datos de Oracle en el almacenamiento de archivos de Azure NetApp y Azure VM.



== Descripción general

Muchas bases de datos empresariales críticas de Oracle todavía están alojadas localmente, y muchas empresas buscan migrar estas bases de datos de Oracle a una nube pública.  A menudo, estas bases de datos de Oracle están centradas en las aplicaciones y, por lo tanto, requieren configuraciones específicas del usuario, una capacidad que falta en muchas ofertas de nube pública de bases de datos como servicio.  Por lo tanto, el panorama actual de bases de datos requiere una solución de base de datos Oracle basada en la nube pública construida a partir de un servicio de almacenamiento y computación escalable y de alto rendimiento que pueda adaptarse a requisitos únicos.  Las instancias de cómputo de máquinas virtuales de Azure y el servicio de almacenamiento de Azure NetApp Files pueden ser las piezas faltantes de este rompecabezas que puede aprovechar para crear y migrar sus cargas de trabajo de base de datos Oracle de misión crítica a una nube pública.



== Máquina virtual de Azure

Las máquinas virtuales de Azure son uno de los diversos tipos de recursos informáticos escalables y a pedido que ofrece Azure.  Normalmente, se elige una máquina virtual cuando se necesita más control sobre el entorno informático del que ofrecen otras opciones.  Las máquinas virtuales de Azure ofrecen una forma rápida y sencilla de crear una computadora con configuraciones específicas necesarias para ejecutar su base de datos Oracle, ya sea para cargas de trabajo que requieren un uso intensivo de memoria o de procesamiento.  Las máquinas virtuales en una red virtual de Azure se pueden conectar fácilmente a la red de su organización, por ejemplo, a través de un túnel VPN seguro.



== Azure NetApp Files (ANF)

Azure NetApp Files es un servicio de Microsoft totalmente administrado que llevará su carga de trabajo de base de datos a la nube de forma más rápida y segura que nunca.  Fue diseñado para cumplir con los requisitos básicos de ejecución de cargas de trabajo de alto rendimiento, como bases de datos Oracle en la nube, y proporciona niveles de rendimiento que reflejan el rango real de demandas de IOPS, baja latencia, alta disponibilidad, alta durabilidad, capacidad de administración a escala y respaldo, recuperación y clonación rápidos y eficientes.  Estas capacidades son posibles porque Azure NetApp Files se basa en sistemas físicos NetApp ONTAP all-flash que se ejecutan dentro del entorno del centro de datos de Azure.  Azure NetApp Files está completamente integrado en los DC y el portal de Azure, y los clientes pueden usar la misma interfaz gráfica y API cómodas para crear y administrar archivos compartidos que con cualquier otro objeto de Azure.  Con los archivos de Azure NetApp , puede desbloquear todas las capacidades de Azure sin riesgos, costos ni tiempo adicionales y confiar en el único servicio de archivos empresariales nativo de Azure.



== Conclusión

Esta documentación describe en detalle cómo implementar, configurar y migrar una base de datos de Oracle con una máquina virtual de Azure y un servicio de almacenamiento de Azure NetApp Files que ofrece rendimiento y durabilidad similares a un sistema local.  Para obtener orientación sobre las mejores prácticas, consulte TR-4780link:https://www.netapp.com/media/17105-tr4780.pdf["Bases de datos Oracle en Microsoft Azure"^] .  Más importante aún, NetApp también proporciona kits de herramientas de automatización que automatizan la mayoría de las tareas necesarias para la implementación, configuración, protección de datos, migración y administración de su carga de trabajo de base de datos Oracle en la nube pública de Azure.  Los kits de herramientas de automatización están disponibles para descargar en el sitio público de GitHub de NetApp :link:https://github.com/NetApp-Automation/["NetApp-Automatización"^] .
