= 
:allow-uri-read: 


. Configurar las credenciales.
. Crear tipos de credenciales. Para las soluciones que involucran ONTAP, debe configurar el tipo de credencial para que coincida con las entradas de nombre de usuario y contraseña; también agregaremos entradas para Cloud Central y AWS.
+
.. Vaya a Administración → Tipos de credenciales y haga clic en Agregar.
.. Proporcione el nombre y la descripción.
.. Pegue el siguiente contenido en Configuración de entrada:
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Pegue el siguiente contenido en Configuración del inyector y haga clic en Guardar:
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. Crear credenciales para ONTAP/CVO/AWS
+
.. Vaya a Recursos → Credenciales y haga clic en Agregar.
.. Ingrese el nombre y los detalles de la organización para las credenciales de ONTAP
.. Seleccione el tipo de credencial que se creó en el paso anterior.
.. En Detalles de tipo, ingrese el nombre de usuario y la contraseña para sus clústeres de origen y CVO, Cloud Central/Manager, clave secreta/de acceso de AWS y token de actualización de Cloud Central.
.. Haga clic en Guardar


. Crear credenciales para Oracle (Fuente)
+
.. Vaya a Recursos → Credenciales y haga clic en Agregar.
.. Ingrese el nombre y los detalles de la organización para el host de Oracle
.. Seleccione el tipo de credencial de la máquina.
.. En Detalles de tipo, ingrese el nombre de usuario y la contraseña para los hosts de Oracle.
.. Seleccione el método de escalada de privilegios correcto e ingrese el nombre de usuario y la contraseña.
.. Haga clic en Guardar


. Crear credenciales para Oracle Destination
+
.. Vaya a Recursos → Credenciales y haga clic en Agregar.
.. Ingrese el nombre y los detalles de la organización para el host de Oracle de recuperación ante desastres
.. Seleccione el tipo de credencial de la máquina.
.. En Detalles de tipo, ingrese el nombre de usuario (ec2-user o si lo ha cambiado del predeterminado, introdúzcalo) y la clave privada SSH.
.. Seleccione el método de escalada de privilegios correcto (sudo) e ingrese el nombre de usuario y la contraseña si es necesario.
.. Haga clic en Guardar



