= 
:allow-uri-read: 


. Configurar las credenciales.
. Crear tipos de credenciales.  Para las soluciones que involucran ONTAP, debe configurar el tipo de credencial para que coincida con las entradas de nombre de usuario y contraseña.
+
.. Vaya a Administración → Tipos de credenciales y haga clic en Agregar.
.. Proporcione el nombre y la descripción.
.. Pegue el siguiente contenido en Configuración de entrada:
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: Destination Cluster Username
  - id: dst_cluster_password
    type: string
    label: Destination Cluster Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
----
.. Pegue el siguiente contenido en Configuración del inyector y luego haga clic en Guardar:
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
----


. Crear credenciales para ONTAP
+
.. Vaya a Recursos → Credenciales y haga clic en Agregar.
.. Ingrese el nombre y los detalles de la organización para las credenciales de ONTAP
.. Seleccione el tipo de credencial que se creó en el paso anterior.
.. En Detalles de tipo, ingrese el nombre de usuario y la contraseña para los clústeres de origen y destino.
.. Haga clic en Guardar


. Crear credenciales para Oracle
+
.. Vaya a Recursos → Credenciales y haga clic en Agregar.
.. Introduzca el nombre y los detalles de la organización de Oracle
.. Seleccione el tipo de credencial de la máquina.
.. En Detalles de tipo, ingrese el nombre de usuario y la contraseña para los hosts de Oracle.
.. Seleccione el método de escalada de privilegios correcto e ingrese el nombre de usuario y la contraseña.
.. Haga clic en Guardar
.. Repita el proceso si es necesario para una credencial diferente para el host dr_oracle.



