---
sidebar: sidebar 
permalink: mysql/tr-4722.html 
keywords:  
summary:  
---
= TR-4722: Prácticas recomendadas para bases de datos MySQL en NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

[role="lead"]
MySQL y sus variantes, incluidas MariaDB y Percona, se utilizan ampliamente para muchas aplicaciones empresariales.  Estas aplicaciones van desde sitios de redes sociales globales y sistemas de comercio electrónico masivos hasta sistemas de alojamiento SMB que contienen miles de instancias de bases de datos.  Este documento describe los requisitos de configuración y proporciona orientación sobre el ajuste y la configuración del almacenamiento para implementar MySQL en el software de administración de datos NetApp ONTAP .  Para determinar si el entorno, las configuraciones y las versiones especificadas en este informe son compatibles con su entorno, consulte la herramienta Matriz de interoperabilidad (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["TR-4722: Prácticas recomendadas para bases de datos MySQL en NetApp ONTAP"^]
