---
sidebar: sidebar 
permalink: automation/automation-ora-clone-gcnv-asm.html 
keywords: Oracle, GCP, GCNV, Database, clone 
summary: La solución proporciona un kit de herramientas de automatización basado en Ansible para configurar, clonar y actualizar bases de datos clonadas de Oracle desde la base de datos física en espera de Oracle Data Guard alojada en la nube de Google en el almacenamiento de Google Cloud NetApp Volumes con configuración ASM. 
---
= Ciclo de vida automatizado de clones de Oracle en GCNV con ASM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, NetApp

[role="lead"]
La solución proporciona un kit de herramientas de automatización basado en Ansible para configurar, clonar y actualizar bases de datos clonadas de Oracle desde la base de datos física en espera de Oracle Data Guard alojada en la nube de Google en el almacenamiento de Google Cloud NetApp Volumes con configuración ASM.



== Objetivo

El aprovechamiento de los clones rápidos de la base de datos Oracle de reserva física en la configuración de Oracle Data Guard para otros casos de uso cumple múltiples propósitos.  Proporciona una base de datos de informes casi en tiempo real y también una copia grabable de la base de datos de producción para fines de desarrollo o UAT.  De esta forma, se pueden eliminar los costosos costos de licencia de Active Data Guard si se acepta una breve demora (10-15 minutos) en la generación de informes.  Ahorra en costos de almacenamiento, particularmente cuando la clonación delgada de volúmenes de datos primarios es una opción.  Este kit de herramientas de automatización basado en Ansible permite a los usuarios configurar, clonar y actualizar bases de datos Oracle clonadas según los cronogramas del usuario para una gestión optimizada del ciclo de vida.  El kit de herramientas se aplica a las bases de datos de Oracle implementadas en la nube pública de Google mediante el almacenamiento de Google Cloud NetApp Volumes (GCNV) y la configuración de la base de datos de Oracle en una configuración de Data Guard.

Esta solución aborda los siguientes casos de uso:

* Configurar los archivos de configuración de la clonación de la base de datos en espera de Oracle para la automatización de Ansible.
* Cree o actualice una base de datos Oracle clonada desde el modo en espera de Data Guard usando el libro de jugadas de Ansible según un cronograma definido por el usuario.




== Audiencia

Esta solución está destinada a las siguientes personas:

* Un DBA que administra bases de datos de Oracle en la nube de Google.
* Un administrador de almacenamiento que gestiona el almacenamiento de Google NetApp Volumes.
* Un propietario de una aplicación a quien le gusta clonar bases de datos Oracle desde el modo de espera de Data Guard para otros casos de uso.




== Licencia

Al acceder, descargar, instalar o utilizar el contenido de este repositorio de GitHub, usted acepta los términos de la Licencia establecidos enlink:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["Archivo de licencia"^] .


NOTE: Existen ciertas restricciones en torno a la producción y/o intercambio de cualquier trabajo derivado del contenido de este repositorio de GitHub.  Asegúrese de leer los términos de la Licencia antes de utilizar el contenido.  Si no está de acuerdo con todos los términos, no acceda, descargue ni utilice el contenido de este repositorio.



== Implementación de la solución



=== Requisitos previos para la implementación

[%collapsible%open]
====
La implementación requiere los siguientes requisitos previos.

....
Ansible controller:
  Ansible v.2.10 and higher
  ONTAP collection 21.19.1
  Python 3
  Python libraries:
    netapp-lib
    xmltodict
    jmespath
....
....
Oracle servers:
  Physical standby Oracle servers in Data Guard configuration
  Clone target Oracle servers with ASM configuration
....

NOTE: Para simplificar, el servidor Oracle de destino clonado debe configurarse de manera idéntica al servidor Oracle en espera, como la pila de software de Oracle y el diseño de directorio para Oracle Home, etc.

====


=== Descargar el kit de herramientas

[%collapsible%open]
====
[source, cli]
----
https://bitbucket.ngage.netapp.com/projects/NS-BB/repos/na_oracle_clone_gcnv/browse
----

NOTE: En este momento, solo los usuarios internos de NetApp con acceso a Bitbucket pueden acceder al kit de herramientas.  Los usuarios externos interesados deben solicitar acceso a su equipo de cuentas o comunicarse con el equipo de ingeniería de soluciones de NetApp .

====


=== Configuración de archivos de hosts de origen y destino de Ansible

[%collapsible%open]
====
El kit de herramientas incluye un archivo de hosts que define los hosts Oracle de origen y destino en los que se ejecuta el playbook de Ansible.  Generalmente, incluye el host de base de datos en espera en la configuración de Data Guard y el host clon de Oracle de destino.  A continuación se muestra un archivo de ejemplo.  Una entrada de host incluye la dirección IP del host de destino, así como la clave ssh para que el usuario acceda al host para ejecutar el comando de clonación o actualización.  Se accede al almacenamiento de Google Cloud NetApp Volumes y se administra a través de gcloud cli.

....
[ora_stdby]
oras ansible_host=172.179.119.75 ansible_ssh_private_key_file=oras.pem
....
....
[ora_clone]
orac ansible_host=52.148.142.212 ansible_ssh_private_key_file=orac.pem
....
....
[gcp]
localhost ansible_connection=local
....
====


=== Configuración de variables globales

[%collapsible%open]
====
A continuación se muestra un ejemplo de un archivo de variable global típico vars.yml que incluye variables que se aplican a nivel global.

....
######################################################################
###### Oracle DB clone on GCNV user configuration variables     ######
###### Consolidate all variables from GCNV, linux and oracle    ######
######################################################################
....
....
############################################
### ONTAP/GCNV specific config variables ###
############################################
....
....
# GCNV credential
key_file: /home/admin/google-cloud-sdk/service_key.json
....
....
# Cloned DB volumes from standby DB
project_id: cvs-pm-host-1p
location: us-west4
protocol: nfsv3
data_vols:
  - "{{ groups.ora_stdby[0] }}-u02"
  - "{{ groups.ora_stdby[0] }}-u03"
  - "{{ groups.ora_stdby[0] }}-u04"
  - "{{ groups.ora_stdby[0] }}-u05"
  - "{{ groups.ora_stdby[0] }}-u06"
  - "{{ groups.ora_stdby[0] }}-u07"
  - "{{ groups.ora_stdby[0] }}-u08"
....
....
nfs_lifs:
  - 10.165.128.197
  - 10.165.128.196
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
....
 nfs_client: 0.0.0.0/0
....
###########################################
### Linux env specific config variables ###
###########################################
....
....
####################################################
### DB env specific install and config variables ###
####################################################
....
....
# Standby DB configuration
oracle_user: oracle
oracle_base: /u01/app/oracle
oracle_sid: NTAP
db_unique_name: NTAP_LA
oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
spfile: '+DATA/{{ db_unique_name }}/PARAMETERFILE/spfile.289.1198520783'
adump: '{{ oracle_base }}/admin/{{ db_unique_name }}/adump'
grid_home: /u01/app/oracle/product/19.0.0/grid
asm_disk_groups:
  - DATA
  - LOGS
....
....
# Clond DB configuration
clone_sid: NTAPDEV
sys_pwd: "XXXXXXXX"
....
....
# Data Guard mode - MaxAvailability or MaxPerformance
dg_mode: MaxAvailability
....

NOTE: Para una implementación de automatización más segura, se puede emplear Ansible Vault para cifrar información confidencial, como contraseñas, tokens de acceso o claves, etc. La solución no cubre la implementación de Ansible Vault, pero está bien documentada en la documentación de Ansible.  Por favor referirse alink:https://docs.ansible.com/ansible/latest/vault_guide/index.html["Protección de datos confidenciales con Ansible Vault"^] Para más detalles.

====


=== Configuración de variables del host

[%collapsible%open]
====
Las variables de host se definen en el directorio host_vars llamado {{ host_name }}.yml y se aplica solo al host en particular.  Para esta solución, solo se configura el archivo de parámetros del host de la base de datos del clon de destino.  Los parámetros de la base de datos en espera de Oracle se configuran en el archivo de variables globales.  A continuación se muestra un ejemplo del archivo de variable de host de base de datos clonada de Oracle de destino orac.yml que muestra una configuración típica.

 # User configurable Oracle clone host specific parameters
....
# Database SID - clone DB SID
oracle_base: /u01/app/oracle
oracle_user: oracle
clone_sid: NTAPDEV
oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
clone_adump: '{{ oracle_base }}/admin/{{ clone_sid }}/adump'
....
....
grid_user: oracle
grid_home: '{{ oracle_base }}/product/19.0.0/grid'
asm_sid: +ASM
....
====


=== Configuración del servidor Oracle de destino de clonación adicional

[%collapsible%open]
====
El servidor Oracle de destino clonado debe tener la misma pila de software Oracle que el servidor Oracle de origen instalado y parcheado.  El usuario de Oracle .bash_profile tiene $ORACLE_BASE y $ORACLE_HOME configurados.  Además, la variable $ORACLE_HOME debe coincidir con la configuración del servidor Oracle de origen.  Si la configuración de ORACLE_HOME de destino es diferente de la configuración del servidor Oracle en espera, cree un enlace simbólico para solucionar las diferencias.  A continuación se muestra un ejemplo.

 # .bash_profile
....
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
       . ~/.bashrc
fi
....
 # User specific environment and startup programs
....
export ORACLE_BASE=/u01/app/oracle
export GRID_HOME=/u01/app/oracle/product/19.0.0/grid
export ORACLE_HOME=/u01/app/oracle/product/19.0.0/NTAP
alias asm='export ORACLE_HOME=$GRID_HOME;export PATH=$PATH:$GRID_HOME/bin;export ORACLE_SID=+ASM'
....

NOTE: Asegúrese de que el parámetro de configuración asm_diskstring en el host de clonación de base de datos incluya todos los puntos de montaje NFS de los volúmenes clonados y las rutas de directorio a los dispositivos de disco.

====


=== Ejecución del libro de jugadas

[%collapsible%open]
====
Hay un total de dos libros de estrategias para ejecutar el ciclo de vida de la clonación de la base de datos de Oracle.  La clonación o actualización de la base de datos se puede ejecutar a pedido o programar como un trabajo crontab.

. Instale los requisitos previos del controlador Ansible (solo una vez).
+
[source, cli]
----
ansible-playbook -i hosts ansible_requirements.yml
----
. Cree y actualice la base de datos clonada a pedido o periódicamente desde crontab con un script de shell para llamar al clon o actualizar el manual de estrategias.
+
[source, cli]
----
ansible-playbook -i oracle_clone_asm_gcnv.yml -u admin -e @vars/vars.yml
----
+
[source, cli]
----
0 */2 * * * /home/admin/na_oracle_clone_gcnv/oracle_clone_asm_gcnv.sh
----


Para clonar bases de datos adicionales, cree un oracle_clone_n_asm_gcnv.yml y un oracle_clone_n_asm_gcnv.sh separados.  Configure los hosts de destino de Ansible, el archivo vars.yml global y el archivo hostname.yml en el directorio host_vars según corresponda.


NOTE: La ejecución del conjunto de herramientas en varias etapas se detiene para permitir que se complete una tarea particular.  Por ejemplo, se detiene durante dos minutos para permitir que se complete la clonación de los volúmenes de la base de datos.  En general, el valor predeterminado debería ser suficiente, pero es posible que sea necesario ajustar el tiempo para una situación o implementación particular.

====


== Dónde encontrar información adicional

Para obtener más información sobre la automatización de soluciones de NetApp , consulte el siguiente sitio weblink:https://docs.netapp.com/us-en/netapp-solutions-dataops/automation/automation-introduction.html["Automatización de soluciones de NetApp ^"^]
