---
sidebar: sidebar 
permalink: automation/db-protection-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Esta página describe el método automatizado para implementar Oracle19c en el almacenamiento NetApp ONTAP . 
---
= Descripción general de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta página describe el método automatizado para implementar Oracle19c en el almacenamiento NetApp ONTAP .



== Protección de datos automatizada para bases de datos Oracle

Las organizaciones están automatizando sus entornos para ganar eficiencia, acelerar las implementaciones y reducir el esfuerzo manual.  Se están utilizando herramientas de gestión de configuración como Ansible para optimizar las operaciones de bases de datos empresariales.  En esta solución, demostramos cómo puede utilizar Ansible para automatizar la protección de datos de Oracle con NetApp ONTAP.  Al permitir que los administradores de almacenamiento, administradores de sistemas y DBA configuren de manera consistente y rápida la replicación de datos en un centro de datos externo o en la nube pública, obtiene los siguientes beneficios:

* Elimine las complejidades de diseño y los errores humanos, e implemente una implementación consistente y repetible y las mejores prácticas.
* Disminuya el tiempo de configuración de la replicación entre clústeres, la creación de instancias de CVO y la recuperación de bases de datos de Oracle
* Aumente la productividad de los administradores de bases de datos, sistemas y almacenamiento
* Proporciona un flujo de trabajo de recuperación de base de datos para facilitar la prueba de un escenario de recuperación ante desastres.


NetApp proporciona a los clientes módulos y roles de Ansible validados para acelerar la implementación, la configuración y la gestión del ciclo de vida de su entorno de base de datos Oracle.  Esta solución proporciona instrucciones y código de libro de estrategias de Ansible para ayudarle a:



=== Replicación local a local

* Crear LIF entre clústeres en origen y destino
* Establecer peering entre clústeres y vservidores
* Crear e inicializar SnapMirror de volúmenes de Oracle
* Cree un programa de replicación a través de AWX/Tower para binarios, bases de datos y registros de Oracle
* Restaurar Oracle DB en el destino y poner la base de datos en línea




=== De local a CVO en AWS

* Crear un conector de AWS
* Crear una instancia de CVO en AWS
* Agregar un clúster local a Cloud Manager
* Crear LIF entre clústeres en la fuente
* Establecer peering entre clústeres y vservidores
* Crear e inicializar SnapMirror de volúmenes de Oracle
* Cree un programa de replicación a través de AWX/Tower para binarios, bases de datos y registros de Oracle
* Restaurar Oracle DB en el destino y poner la base de datos en línea


Cuando esté listo, haga clic enlink:db-protection-getting-started.html["Aquí para comenzar con la solución."] .
