---
sidebar: sidebar 
permalink: automation/marketing-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Esta página describe el método automatizado para implementar Oracle19c en el almacenamiento NetApp ONTAP . 
---
= Descripción general de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta página describe el método automatizado para implementar Oracle19c en el almacenamiento NetApp ONTAP .



== Implementación automatizada de Oracle19c para ONTAP en NFS

Las organizaciones están automatizando sus entornos para ganar eficiencia, acelerar las implementaciones y reducir el esfuerzo manual.  Se están utilizando herramientas de gestión de configuración como Ansible para optimizar las operaciones de bases de datos empresariales.  En esta solución, demostramos cómo puede utilizar Ansible para automatizar el aprovisionamiento y la configuración de Oracle 19c con NetApp ONTAP.  Al permitir que los administradores de almacenamiento, administradores de sistemas y DBA implementen de manera consistente y rápida nuevo almacenamiento, configuren servidores de bases de datos e instalen el software Oracle 19c, obtiene los siguientes beneficios:

* Elimine las complejidades de diseño y los errores humanos, e implemente una implementación consistente y repetible y las mejores prácticas.
* Reducir el tiempo de aprovisionamiento de almacenamiento, configuración de hosts de bases de datos e instalación de Oracle
* Aumente la productividad de los administradores de bases de datos, sistemas y almacenamiento
* Habilite el escalado del almacenamiento y las bases de datos con facilidad


NetApp proporciona a los clientes módulos y roles de Ansible validados para acelerar la implementación, la configuración y la gestión del ciclo de vida de su entorno de base de datos Oracle.  Esta solución proporciona instrucciones y código de libro de estrategias de Ansible para ayudarle a:

* Crear y configurar el almacenamiento NFS de ONTAP para Oracle Database
* Instalar Oracle 19c en RedHat Enterprise Linux 7/8 u Oracle Linux 7/8
* Configurar Oracle 19c en el almacenamiento NFS de ONTAP


Para obtener más detalles o comenzar, consulte los videos de descripción general a continuación.



=== Implementaciones de AWX/Torre

Parte 1: Primeros pasos, requisitos, detalles de automatización y configuración inicial de AWX/Tower

.Implementación de AWX
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
Parte 2: Variables y ejecución del libro de jugadas

.AWX Playbook Run
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


=== Implementación de CLI

Parte 1: Primeros pasos, requisitos, detalles de automatización y configuración del host de control de Ansible

.Implementación de CLI
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
Parte 2: Variables y ejecución del libro de jugadas

.Ejecución del libro de estrategias CLI
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]